Routes crimes fonctionnelles, recetter routes bikes
MisterAzix/hetic-urban-data-analytics pull request #14
Opened 2024-12-17 13:58 UTC by CharlesLambret

2024-12-17 14:31 UTC, LostLemonCurd commented
Est-ce qu'il ne manque pas le dossier routes ? Les routes ne sont pas accessibles actuellement

2024-12-18 08:05 UTC, MisterAzix requested changes
To rebase + Pourquoi les `POST`, `PUT`, `DELETE` ? Pas d'utilité à l'instant T, donc code mort. On évite ;)

2024-12-18 08:05 UTC, MisterAzix commented on jest.config.js
?

2024-12-18 08:05 UTC, MisterAzix commented on jest.setup.js
?

2024-12-18 09:58 UTC, closed without merging